# Generated by Django 4.2.5 on 2023-09-23 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_book_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='MRP_price',
        ),
    ]
